In [54]:
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import metrics 
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import VotingClassifier

In [ ]:
df = pd.read_csv('labeled_data_1.csv')
df.columns

Index(['id', 'label', 'tweet', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

Test Train Split

In [ ]:
from sklearn.utils import shuffle
df = shuffle(df)
X_train, X_test, y_train, y_test = train_test_split(df['tweet'], 
                                                    df['label'], 
                                                    random_state=1)

In [46]:
label=df['label'].tolist()
count0=0
count1=0
count2=0
for i in label:
  if i==0:
    count0=count0+1
  if i==1:
    count1=count1+1
  if i==2:
    count2=count2+1
print('Class 0:',count0,'\nClass 1:',count1,'\nClass 2:',count2)

Class 0: 1430 
Class 1: 19190 
Class 2: 4163


Tokenization


In [ ]:
# Instantiate the CountVectorizer method
count_vector = CountVectorizer(stop_words = 'english')

# Fit the training data and then return the matrix
training_data = count_vector.fit_transform(X_train)

# Transform testing data and return the matrix. Note we are not fitting the testing data into the CountVectorizer()
testing_data = count_vector.transform(X_test)

Extra Trees Classifier

In [ ]:
ExtraTrees = ExtraTreesClassifier(n_estimators=220, max_depth=None, min_samples_split=2, random_state=0)
ExtraTrees.fit(training_data, y_train)
predictions_2 = ExtraTrees.predict(testing_data)

print('Accuracy score: ', format(accuracy_score(y_test, predictions_2)))
#print('Precision score: ', format(precision_score(y_test, predictions_2)))
#print('Recall score: ', format(recall_score(y_test, predictions_2)))
#print('F1 score: ', format(f1_score(y_test, predictions_2)))

Accuracy score:  0.8897675919948353


In [50]:
cm=metrics.confusion_matrix(y_test, predictions_2)
c=cm / cm.astype(np.float).sum(axis=1)
c[0]=c[0]*count0
c[1]=c[1]*count1
c[2]=c[2]*count2
c=c.astype(int)
print(c)


[[  305    75    38]
 [ 3557 18390  2479]
 [  152   164  3348]]


Gradient Boosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=300, learning_rate=1.0,max_depth=1, random_state=0)
clf.fit(training_data, y_train)
predictions_3 = clf.predict(testing_data)
print('Accuracy score: ', format(accuracy_score(y_test, predictions_3)))
#print('Precision score: ', format(precision_score(y_test, predictions_3)))
#print('Recall score: ', format(recall_score(y_test, predictions_3)))
#print('F1 score: ', format(f1_score(y_test, predictions_3)))

Accuracy score:  0.8988056810845707


In [52]:
cm2=metrics.confusion_matrix(y_test, predictions_3)
c2=cm2 / cm2.astype(np.float).sum(axis=1)
c2[0]=c2[0]*count0
c2[1]=c2[1]*count1
c2[2]=c2[2]*count2
c2=c2.astype(int)
print(c2)

[[  273    72    62]
 [ 2641 18450  2516]
 [   81   127  3544]]


Ada Boost Classifier


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
AdaBoost = AdaBoostClassifier(n_estimators=100, random_state=7)
AdaBoost.fit(training_data, y_train)
predictions_4 = AdaBoost.predict(testing_data)
print('Accuracy score: ', format(accuracy_score(y_test, predictions_4)))
#print('Precision score: ', format(precision_score(y_test, predictions_4)))
#print('Recall score: ', format(recall_score(y_test, predictions_4)))
#print('F1 score: ', format(f1_score(y_test, predictions_4)))

Accuracy score:  0.9059070367979342


In [53]:
cm3=metrics.confusion_matrix(y_test, predictions_4)
c3=cm3 / cm3.astype(np.float).sum(axis=1)
c3[0]=c3[0]*count0
c3[1]=c3[1]*count1
c3[2]=c3[2]*count2
c3=c3.astype(int)
print(c3)

[[  249    74    62]
 [ 2317 18295  3349]
 [  175    43  3902]]


Voting


In [55]:
clf3 = VotingClassifier(estimators=[('Ab', AdaBoost), ('Gb', clf), ('Et', ExtraTrees)])
clf3.fit(training_data, y_train)
predictions_5 = clf3.predict(testing_data)
print('Accuracy score: ', format(accuracy_score(y_test, predictions_5)))

Accuracy score:  0.9052614590058102


In [56]:
cm4=metrics.confusion_matrix(y_test, predictions_4)
c4=cm4 / cm4.astype(np.float).sum(axis=1)
c4[0]=c4[0]*count0
c4[1]=c4[1]*count1
c4[2]=c4[2]*count2
c4=c4.astype(int)
print(c4)

[[  249    74    62]
 [ 2317 18295  3349]
 [  175    43  3902]]
